baseURL = 'https://wasmvision.com/'
languageCode = 'en-us'
title = 'wasmVision'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"

[markup.goldmark.renderer]
unsafe = true

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name ="Mastodon"
	url = "https://mastodon.social/@wasmvision"
	icon = "fab fa-mastodon"
		desc = "Follow us on Mastodon to get the latest news!"
[[params.links.user]]
	name ="Bluesky"
	url = "https://bsky.app/profile/wasmvision.com"
	icon = "fab fa-bluesky"
		desc = "You can also follow us on Bluesky"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/wasmvision/wasmvision"
	icon = "fab fa-github"
        desc = "Development takes place here!"

[params.mermaid]
enable = true
